# Generated by Django 5.2 on 2025-12-03 06:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditDemoRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeric_value", models.IntegerField()),
                ("message", models.TextField()),
                ("structured_payload", models.JSONField(default=dict)),
                ("identity_number", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Demo Record",
                "verbose_name_plural": "Audit Demo Records",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditEventOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_label", models.CharField(max_length=255)),
                ("object_pk", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("locked", "Locked"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("dlq", "Dead Letter"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Event Outbox",
                "verbose_name_plural": "Audit Event Outboxes",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="audit_trail_status_eda37d_idx",
                    ),
                    models.Index(
                        fields=["model_label", "object_pk"],
                        name="audit_trail_model_l_775514_idx",
                    ),
                ],
            },
        ),
    ]
